package Base;

import data.Account;
import data.AccountManager;
import javax.swing.JOptionPane;

/**
 *
 * @author quang
 */
public class Login extends javax.swing.JFrame {

    AccountManager accountManager = new AccountManager();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfUsername = new javax.swing.JTextField();
        jbtnLogin = new javax.swing.JButton();
        jbtnSignUp = new javax.swing.JButton();
        jpwPassword = new javax.swing.JPasswordField();
        Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfUsername.setBackground(new java.awt.Color(255, 255, 255));
        jtfUsername.setBorder(null);
        jtfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 200, 30));

        jbtnLogin.setBackground(new java.awt.Color(0, 153, 204));
        jbtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLogin.setText("Login");
        jbtnLogin.setBorder(null);
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 80, 40));

        jbtnSignUp.setBackground(new java.awt.Color(0, 153, 204));
        jbtnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSignUp.setText("Sign up");
        jbtnSignUp.setBorder(null);
        jbtnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 80, 30));

        jpwPassword.setBackground(new java.awt.Color(255, 255, 255));
        jpwPassword.setBorder(null);
        jpwPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jpwPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 216, 210, 20));

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/Frame 1.png"))); // NOI18N
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 630, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsernameActionPerformed

    }//GEN-LAST:event_jtfUsernameActionPerformed

    private void jpwPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwPasswordActionPerformed

    }//GEN-LAST:event_jpwPasswordActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        if (jtfUsername.getText().isEmpty() || jpwPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập và mật khẩu không được để trống");
        } else if (Account.login(accountManager.getAccounts(), jtfUsername.getText(), jpwPassword.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập hoặc mật khẩu không chính xác");
        }

    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSignUpActionPerformed
        SignUp su2 = new SignUp();
        su2.show();
        
        dispose();
        
    }//GEN-LAST:event_jbtnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnSignUp;
    private javax.swing.JPasswordField jpwPassword;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
