package Base;

import data.Account;
import data.AccountManager;
import javax.swing.JOptionPane;

/**
 *
 * @author quang
 */
public class SignUp extends javax.swing.JFrame {

    AccountManager accountManager = new AccountManager();

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfUsername = new javax.swing.JTextField();
        jtfUsername1 = new javax.swing.JTextField();
        jpwPassword = new javax.swing.JPasswordField();
        jpwConfirm = new javax.swing.JPasswordField();
        jbtnSignUp = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        SignUp = new javax.swing.JLabel();

        jtfUsername.setBackground(new java.awt.Color(255, 255, 255));
        jtfUsername.setBorder(null);
        jtfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsernameActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfUsername1.setBackground(new java.awt.Color(255, 255, 255));
        jtfUsername1.setBorder(null);
        jtfUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsername1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtfUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 200, 20));

        jpwPassword.setBackground(new java.awt.Color(255, 255, 255));
        jpwPassword.setBorder(null);
        jpwPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jpwPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 210, 20));

        jpwConfirm.setBackground(new java.awt.Color(255, 255, 255));
        jpwConfirm.setBorder(null);
        jpwConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpwConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(jpwConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 210, 20));

        jbtnSignUp.setBackground(new java.awt.Color(0, 153, 255));
        jbtnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSignUp.setText("Sign up");
        jbtnSignUp.setBorder(null);
        jbtnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 90, 40));

        jbtnLogin.setBackground(new java.awt.Color(0, 153, 255));
        jbtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLogin.setText("Login");
        jbtnLogin.setBorder(null);
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 90, 30));

        SignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/Frame 2.png"))); // NOI18N
        getContentPane().add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsernameActionPerformed

    }//GEN-LAST:event_jtfUsernameActionPerformed

    private void jtfUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsername1ActionPerformed

    }//GEN-LAST:event_jtfUsername1ActionPerformed

    private void jpwPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwPasswordActionPerformed

    }//GEN-LAST:event_jpwPasswordActionPerformed

    private void jpwConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwConfirmActionPerformed

    }//GEN-LAST:event_jpwConfirmActionPerformed

    private void jbtnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSignUpActionPerformed
        if (jtfUsername1.getText().isEmpty() || jpwPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập và mật khẩu không được để trống");
        } else if (jpwConfirm.getText().equals(jpwPassword.getText()) == false) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu xác nhận không trùng khớp");
        } else if (Account.register(accountManager.getAccounts(), jtfUsername1.getText(), jpwPassword.getText())) {
            accountManager.saveAccounts();
            JOptionPane.showMessageDialog(rootPane, "Đăng kí thành công!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tài khoản đã tồn tại!");
        }


    }//GEN-LAST:event_jbtnSignUpActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
       Login lg2 = new Login();
       lg2.show();
       dispose();
    }//GEN-LAST:event_jbtnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignUp;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnSignUp;
    private javax.swing.JPasswordField jpwConfirm;
    private javax.swing.JPasswordField jpwPassword;
    private javax.swing.JTextField jtfUsername;
    private javax.swing.JTextField jtfUsername1;
    // End of variables declaration//GEN-END:variables
}
